[global]
   workgroup = WORKGROUP
   server string = Pure Samba Alpine
   security = user
   map to guest = Bad User
   unix charset = UTF-8

   # PERFORMANCE
   use sendfile = yes
   aio read size = 1
   aio write size = 1

   strict locking = no
   posix locking = no
   oplocks = yes
   level2 oplocks = yes
   kernel oplocks = yes

   min receivefile size = 16384
   read raw = yes
   write raw = yes

   # Reduz latência
   server min protocol = SMB2
   client min protocol = SMB2

   # Remove NetBIOS (veloz e atual)
   disable netbios = yes
   smb ports = 445

   # Cache de diretórios
   directory name cache size = 2048

[public]
   path = /share/public
   browseable = yes
   writable = yes
   guest ok = yes
   create mask = 0666
   directory mask = 0777

[private]
   path = /share/private
   browseable = yes
   writable = yes
   guest ok = no
   valid users = homelab
   create mask = 0660
   directory mask = 0770
