server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/;

    # Ativa a listagem de diretorios
    autoindex on;
    autoindex_localtime on;  # Mostra a hora local
    autoindex_exact_size off;  # Nao mostra o tamanho exato do arquivo, apenas uma aproximacao (KB, MB, GB)

    # Definindo os tipos MIME corretamente
    types {
        application/pdf   pdf;
        application/epub+zip epub;
    }

    # Customizacao da listagem de diretorrios
    location / {
        autoindex_format html;  # Formato de listagem de diretorios
        # Nao ha° necessidade de definir o index.html aqui, ja que a listagem sera gerada automaticamente
    }

    # Servindo o estilo CSS para a listagem de diret√≥rios
    location /style.css {
        root /usr/share/nginx/html;  # Servindo o arquivo CSS para a listagem
    }

    # Configuracoes de seguranca: Impede o acesso a arquivos ocultos
    location ~ /\.ht {
        deny all;  # Impede o acesso a arquivos ocultos (ex: .htaccess)
    }

    # Seguranca adicional: Previne o navegador de interpretar arquivos como outro tipo
    add_header X-Content-Type-Options nosniff;

    # Configuracao de cache opcional (pode ser util para PDFs, EPUBs, etc)
    location ~* \.(pdf|epub)$ {
        add_header Cache-Control "public, max-age=86400";  # Armazenamento em cache por 24 horas
    }

    # Configuracoes adicionais podem ser aplicadas conforme necessario
}

