services:
  calibre-init:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre-init
    command: >
      bash -c "
      echo 'Criando biblioteca Calibre em /books...' &&
      calibredb add --empty --library-path=/books &&
      echo 'metadata.db criado com sucesso!'
      "
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./library:/books
    restart: "no"

