services:
  calibreweb:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      # - DOCKER_MODS=linuxserver/mods:universal-calibre # ativa os recursos do calibre
    volumes:
      - ./library:/books
      - ./app:/config
    ports:
      - "8083:8083"
    restart: unless-stopped
